# BUUSEC 2019 Sql XSS 1

version: "2"

services:

  web:
    build: ./web
    image: glzjin/buusec_2019_sql_xss_1
    restart: always
    ports:
      - "127.0.0.1:8302:80"
    environment:
      - PASSWORD=123456
      - FLAG=flag{glzjin_wants_a_girl_firend}

  xssbot:
    build: ./xssbot
    image: glzjin/buusec_2019_sql_xss_1_xssbot
    restart: always
    depends_on:
      - web
    environment:
      - LOGIN_URL=http://web/backend/login.php
      - PASSWORD=123456
      - ADMIN_URL=http://web/backend/treehole_list.php
      - DOMAIN=web
      - REFERER_URL=http://web/backend/admin.php
